### ISSUE TITLE
Unable to set comment_parent to 0

### ISSUE THREAD

**Issue by IvanRF** [Yoast/comment-hacks#10]
Hi, I'm testing this plugin and I've found this:

Bugs:
- Setting the comment_parent as 0 does not work, neither leaving the field empty. Sometimes users post comments as replies to other comment, but they are not related. Currently, I manually set the comment_parent in the DB to 0.

Improvements:
- add the Comment Parent field in the Quick Edit too.
- I like the Clean emails idea, but it would be nice to have the option to add the author IP since it gives information about author location.
- the only way to email all commenters is if the user has "Show Toolbar when viewing site" enabled. I personally disable that, and there is no other way to use your feature. You should add it in the post links, like you do with individual emails.
- add i18n support (WPML) for the min length error message.

**Comment by jdevalk** [comment]
Hey @IvanRF "slightly" late in responding to this but:

- Quick edit: that's kinda hard, so no for now.
- That's a no for now too, but I will fix that you can actually disable them properly.
- That's the best spot I can think of for adding it... 
- The min length error message actually has full i18n support, but is a setting the plugin settings.

That leaves nothing to fix, so closing.

**Comment by IvanRF** [comment]
@jdevalk what about the bug?

**Comment by jdevalk** [comment]
You're right, that's still a bug, reopening. Next time, if you could please help me by creating separate issues for separate problems ;)

**Comment by IvanRF** [comment]
Thanks! I will do it next time 😄
