### ISSUE TITLE
Use of deprecated get_currentuserinfo()

### ISSUE THREAD

**Issue by JiveDig** [Yoast/comment-hacks#12]
NOTICE: GET_CURRENTUSERINFO IS <STRONG>DEPRECATED</STRONG> SINCE VERSION 4.5! USE WP_GET_CURRENT_USER() INSTEAD. IN /USERS/JIVEDIG/SITES/WELLNESSMAMA.DEV/WP-INCLUDES/FUNCTIONS.PHP ON LINE 3658

I always work with DEBUG on and Query Monitor active. Would love to get rid of these deprecated notices when using this plugin. Thanks!

**Comment by jdevalk** [comment]
This has already been fixed in trunk and will be gone with the 1.2 release.
