### ISSUE TITLE
Add Reply-To header on comment notification

### ISSUE THREAD

**Issue by IvanRF** [Yoast/comment-hacks#23]
The comment author is currently included in the mail content of comment notifications, but would be better to have it in the email Headers too.

Would it be possible to add to email Headers a simple "Reply-To" with the Author email when a comment notification is sent?

I use comment moderation and sometimes a clarification from the author is needed. Adding "Reply-To" header will make easier to send a reply to the user which posted a comment.

Related: [WP Core closed ticket](https://core.trac.wordpress.org/ticket/36834), rachelbaker said:

> We do have a filter, `comment_notification_headers`, that would allow a plugin to implement your request.

**Comment by jdevalk** [comment]
@IvanRF the reply-to header is set by default in `wp_notify_postauthor` in core, as [you can see here](https://github.com/WordPress/WordPress/blob/master/wp-includes/pluggable.php#L1506)... So I don't really understand what you mean?

**Comment by jdevalk** [comment]
Closing for now.

**Comment by IvanRF** [comment]
I can see in the code you linked that Reply-To seems to be implemented, but I have the latest Wordpress installed and nothing from that code is applied when a comment notification is sent to me.
For example, `$comment->comment_author` is never empty so From should be
`$from = "From: \"$comment->comment_author\" <$wp_email>";`
but in the Headers sent to me says:
`From: WordPress <wordpress@ivanrf.com>`

Thus, the author name is not in the From and there is no Reply-To either. I'm not sure what is happening here. I search in the wp-content folder for "comment_notification_headers" but only this plugin use it, so I don't think another plugin or my theme is messing with the headers.

**Comment by jdevalk** [comment]
Hmm it's not triggered indeed. I've added code in Comment Hacks to do this.

**Comment by IvanRF** [comment]
Thanks for adding this!
Did you figured out why the WP core is not working? is it a bug? (I use comment moderation, is related to that?)
