### ISSUE TITLE
[Feature Request] Improve Notification copy and language when paging comments is enabled

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/comment-hacks#30]
**When Paging Comments is enabled a notification is shown** 

![screen shot 2018-02-07 at 2 45 32 pm](https://user-images.githubusercontent.com/8238074/35972762-1cc13000-0ca1-11e8-80e5-4510210e95a5.png)

**which prompts the user to visit the comments settings section and unclick the "Break Comments into pages" part. However, the way that notification is written seems to imply the user should click the box above it.** 

![screen_shot_2018-02-07_at_2_45_39_pm](https://user-images.githubusercontent.com/8238074/35972829-5e8883d0-0ca1-11e8-902d-dfb2540ac693.png)

**Replace the phrase** 

> Simply uncheck the box before "Break Comments into pages...

**With**

> To resolve uncheck the box in front of the "Break Comments into pages..." field.

**Makes it more clear and provides a better user experience.**

**Comment by jdevalk** [comment]
This is in the wrong repo, I think. Reopened the original.
