### ISSUE TITLE
Comment Hacks email feature no longer appears

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/comment-hacks#76]
When reviewing the Comment overview page or visiting a page with a comment, there is expected to be an option to send an email. As shown in the images below. It does not appear.

_Email Comment Icon on front-end_

<img width="465" alt="1" src="https://user-images.githubusercontent.com/8238074/112664809-c0412000-8e30-11eb-81a9-c2fddadc49e7.png">

_Email Feature in comment overview page_

<img width="465" alt="2" src="https://user-images.githubusercontent.com/8238074/112664992-f1b9eb80-8e30-11eb-94c7-25bed616e70a.png">

**Steps to Reproduce**

1. Install Comment Hacks
2. Make a comment on a post
3.  Look at front-end and see no email icon appears

<img width="1055" alt="3" src="https://user-images.githubusercontent.com/8238074/112665042-026a6180-8e31-11eb-85d7-4150735b3e5f.png">

4.  Go to Comments and review the comments listed. Mouse over them and see no email option appears.

 
![4](https://user-images.githubusercontent.com/8238074/112665399-64c36200-8e31-11eb-8199-c16c566ecde9.jpg)

**Tested With**
WordPress: 5.7
Comment Hacks: 1.6

**Regression**
According to this thread it appears so: https://wordpress.org/support/topic/no-emial-button-in-wp-5-5/. However, I did not test this.

**Comment by indigonl** [comment]
Same here.

**Comment by barates** [comment]
Same here!

**Comment by tacoverdo** [comment]
According to [this report in the forums](https://wordpress.org/support/topic/no-emial-button-in-wp-5-5/), this may have been the case since WP5.5.

**Comment by barates** [comment]
So, when is version 1.7 being released? As far as i can tell, all tests have been successful.
Eagerly awaiting the correct functionality!
Thank you in advance
