### ISSUE TITLE
Redirect not working

### ISSUE THREAD

**Issue by inspiremeland** [Yoast/comment-hacks#9]
Just found this plugin and I would like it to work. For some reason when I got a new comment, the new user is not redirected to my subscribe page... 
It should redirect the reader to http://inspiremeland.com/4472-2/, but it isn't redirecting for some reason..

**Comment by jdevalk** [comment]
@inspiremeland did you set the redirect in the settings? And are you still experiencing this issue? If so, please reopen with more details :)
